In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv3D, MaxPooling3D, Dropout, BatchNormalization
from keras.utils import to_categorical
import numpy as np

Using Theano backend.


In [2]:
# function to generate 3d arrays
def rand_generator():
    arr = np.zeros((3, 3, 3))
    for i in range(3):
        for j in range(3):
            for k in range(3):
                a = np.random.uniform(-1.0, 1.0)
                b = np.random.uniform(-1.0, 1.0)
                arr[i][j][k] = np.random.uniform(a,b)
    return arr

In [3]:
# initialising training and validation sets
X_train = []
X_valid = []

In [4]:
# append the 3d arrays as much as the range specified
for i in range(50):
    X_train.append(rand_generator())

In [5]:
# do it also for the validation set
for i in range(5):
    X_valid.append(rand_generator())

In [6]:
# check the training set
X_train

[array([[[ 0.57170526,  0.66946852, -0.45130973],
         [ 0.59776887, -0.66994644,  0.11910472],
         [ 0.70422081, -0.66427762, -0.2386768 ]],
 
        [[ 0.47354382, -0.50282662, -0.377281  ],
         [ 0.15568808, -0.70586821, -0.19054337],
         [-0.1903514 ,  0.43549803, -0.38260359]],
 
        [[ 0.4066992 ,  0.35364381,  0.16028945],
         [ 0.53907602,  0.62874362, -0.12178283],
         [-0.17201537, -0.85707307, -0.08415655]]]),
 array([[[-0.40747805, -0.0360478 , -0.5038349 ],
         [-0.17652631,  0.75032159,  0.30859869],
         [ 0.32484897,  0.36416932, -0.02588176]],
 
        [[ 0.22116118,  0.10589476,  0.10872618],
         [ 0.12064726,  0.09938653,  0.84688887],
         [ 0.26418056, -0.8676255 ,  0.4196384 ]],
 
        [[ 0.5540582 , -0.48738675,  0.7510368 ],
         [-0.26127756, -0.32148818,  0.90094586],
         [ 0.79369125, -0.86871223, -0.16950203]]]),
 array([[[ 0.46836439, -0.69361781,  0.55383275],
         [ 0.63288304, -0.734677

In [7]:
X_train[5]

array([[[ 0.17235825, -0.5674673 ,  0.34132629],
        [ 0.25152649,  0.30713571, -0.58623369],
        [-0.09341131,  0.01677259,  0.72804405]],

       [[-0.59962181,  0.81736862, -0.49064091],
        [-0.15757093,  0.5264529 , -0.23196285],
        [-0.04693414,  0.21307229, -0.42162937]],

       [[ 0.48736582,  0.1222117 , -0.24642777],
        [ 0.68776555,  0.18107133,  0.31896859],
        [-0.44425145, -0.02956018,  0.35536208]]])

In [8]:
X_valid

[array([[[-0.23574731,  0.32934496,  0.32171864],
         [-0.14900452,  0.31695301,  0.23004723],
         [ 0.69328057,  0.02259911,  0.2920925 ]],
 
        [[ 0.22096206,  0.08567156, -0.75413655],
         [ 0.92015639,  0.44254659, -0.78400998],
         [ 0.27306303,  0.86924626, -0.4359595 ]],
 
        [[-0.90120436, -0.00113393,  0.51129112],
         [-0.07931352, -0.49634287,  0.87991339],
         [-0.16792566,  0.02340965,  0.24702595]]]),
 array([[[ 0.79904616, -0.38225679,  0.2251083 ],
         [ 0.71935774, -0.76929608,  0.37028523],
         [ 0.09266906, -0.62195827, -0.17709545]],
 
        [[-0.66022277, -0.22335073,  0.36705523],
         [ 0.33271956, -0.55588475,  0.25830671],
         [ 0.29676644,  0.22008263,  0.38332946]],
 
        [[ 0.15634965, -0.49380016, -0.49729804],
         [ 0.3044753 , -0.20989073,  0.08446627],
         [ 0.51437039,  0.77333653, -0.40033809]]]),
 array([[[-0.24871756, -0.27414472, -0.71803205],
         [-0.52584689, -0.494632

In [9]:
X_valid[2]

array([[[-0.24871756, -0.27414472, -0.71803205],
        [-0.52584689, -0.49463294, -0.34163333],
        [-0.17563282,  0.17875767,  0.14555571]],

       [[ 0.10365548,  0.03180875, -0.5259725 ],
        [ 0.27525157, -0.36921331,  0.52762507],
        [-0.41698783,  0.86379354, -0.76220542]],

       [[ 0.02727881, -0.92627662,  0.23601806],
        [ 0.06079931,  0.29825223, -0.17820162],
        [ 0.52257874, -0.45223656, -0.2497576 ]]])

In [10]:
# initialize the labels for the training and validation sets, where in this case the
# labels will be the maximum values for each array
target_train = []
target_valid = []

In [11]:
# function to find the maximum value in the array and append to the labels set
def find_max(array):
    for i in range(50):
        target_train.append(np.max(array[i]))

In [12]:
# also for the validation set
def find_max2(array):
    for i in range(5):
        target_valid.append(np.max(array[i]))

In [13]:
find_max(X_train)
find_max2(X_valid)

In [14]:
print(target_train)

[0.7042208139257635, 0.9009458554140047, 0.8856426249479883, 0.7640256132856416, 0.8521915478106419, 0.8173686175261444, 0.6876826584282323, 0.7023703242941252, 0.8544834761759821, 0.9302067006302187, 0.8257895598702496, 0.7238560865597743, 0.7275994765735723, 0.9482844895641372, 0.7704309011098232, 0.8653300017280093, 0.6699173796077176, 0.7774787875974101, 0.6758277887129939, 0.9567389847738323, 0.8400534799764621, 0.8732527489325699, 0.7974592570671964, 0.611113205564604, 0.8395616291479273, 0.8480260930924731, 0.7499872603011307, 0.9179469353851941, 0.9606313661859079, 0.9168790404957141, 0.8813855243724572, 0.744281864236225, 0.6710235280148957, 0.9662889119046784, 0.8036588589728321, 0.8895732948162511, 0.6743455172279763, 0.8805015156785414, 0.6019397530497872, 0.7590085243935981, 0.7614402633258026, 0.8230865939901697, 0.8355089006506959, 0.9854742292088606, 0.8287389581391084, 0.8497646279168867, 0.804387970033953, 0.7686639107961984, 0.9568919989077586, 0.6988313785471346]


In [15]:
print(target_valid)

[0.9201563856885467, 0.7990461603107153, 0.8637935381689377, 0.8818824662224346, 0.8797021000947794]


In [16]:
np.shape(X_train)

(50, 3, 3, 3)

In [17]:
np.shape(X_valid)

(5, 3, 3, 3)

In [18]:
# reshape to add the channel value, where in this case is 1
X_train = np.reshape(X_train,(50,3,3,3,1))
X_valid = np.reshape(X_valid,(5,3,3,3,1))

In [27]:
np.shape(X_train)

(50, 3, 3, 3, 1)

In [28]:
np.shape(target_train)

(50,)

In [29]:
np.shape(target_valid)

(5,)

In [31]:
# Create the model
model = Sequential([
    Conv3D(32, kernel_size=(3, 3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(3,3,3,1)),
    BatchNormalization(center=True, scale=True),
    Dropout(0.5),
    Conv3D(64, kernel_size=(3, 3, 3), activation='relu', kernel_initializer='he_uniform'),
    MaxPooling3D(pool_size=(2, 2, 2)),
    BatchNormalization(center=True, scale=True),
    Dense(200, activation='relu', kernel_initializer='he_uniform'),
    Dense(100, activation='relu', kernel_initializer='he_uniform'),
    Dense(50, activation='softmax')

])

In [32]:
# Compile the model
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=keras.optimizers.Adam(lr=0.001),
              metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv3d_3 (Conv3D)            (None, 1, 1, 1, 32)       896       
_________________________________________________________________
batch_normalization_3 (Batch (None, 1, 1, 1, 32)       128       
_________________________________________________________________
dropout_2 (Dropout)          (None, 1, 1, 1, 32)       0         
_________________________________________________________________
conv3d_4 (Conv3D)            (None, -1, -1, -1, 64)    55360     
_________________________________________________________________
max_pooling3d_2 (MaxPooling3 (None, -1, -1, -1, 64)    0         
_________________________________________________________________
batch_normalization_4 (Batch (None, -1, -1, -1, 64)    256       
_________________________________________________________________
dense_4 (Dense)              (None, -1, -1, -1, 200)  

In [33]:
# Fit data to model
history = model.fit(np.array(X_train), np.array(target_train),
            epochs=10,
            verbose=1,
#             validation_split=0.10
            validation_data=(np.array(X_valid), np.array(target_valid))
            )

ValueError: Error when checking target: expected dense_6 to have 5 dimensions, but got array with shape (50, 1)